version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
            - shared-proxy

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        restart: on-failure
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.teapot.rule=Host(`teapot.418.ovh`)"
                - "traefik.docker.network=shared-proxy"
                - "traefik.http.routers.teapot.tls=true"
                - "traefik.http.routers.teapot.tls.certresolver=mytlschallenge"
                - "traefik.http.services.teapot.loadbalancer.server.port=80"
        networks:
            - shared-proxy

volumes:
    db_data: {}

networks:
    shared-proxy:
        external: true